version: '3.8'

services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - app-network
networks:
  app-network:
    driver: bridge